name: test_macros
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-180

dependencies:
  collection: ^1.18.0
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  json: ^0.20.2
  macros: ^0.1.0-main.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
